import { StyleSheet } from "react-native";
import { PHONE_WIDTH, PHONE_HEIGHT } from "./constants";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#F2F2F7",
  },
  navHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    paddingVertical: 10,
  },
  backBtn: {
    width: 40,
    height: 40,
    justifyContent: "center",
    alignItems: "center",
  },
  navTitle: {
    fontSize: 17,
    fontWeight: "600",
    color: "#1A1A1A",
  },
  scrollContent: {},
  slideWrapper: {
    alignItems: "center",
    paddingHorizontal: 20,
  },
  slideLabel: {
    fontSize: 13,
    fontWeight: "600",
    color: "#888",
    marginBottom: 8,
    letterSpacing: 0.5,
    textTransform: "uppercase",
  },

  // Frame
  frameContainer: {
    width: PHONE_WIDTH + 32,
    borderRadius: 28,
    overflow: "hidden",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.2,
    shadowRadius: 20,
    elevation: 10,
  },
  frameGradient: {
    paddingTop: 32,
    paddingBottom: 20,
    alignItems: "center",
  },
  captionArea: {
    alignItems: "center",
    marginBottom: 20,
    paddingHorizontal: 24,
  },
  captionText: {
    fontSize: 22,
    fontWeight: "800",
    color: "#FFFFFF",
    textAlign: "center",
    lineHeight: 28,
  },
  subcaptionText: {
    fontSize: 14,
    color: "rgba(255,255,255,0.7)",
    textAlign: "center",
    marginTop: 6,
  },

  // Phone
  phoneScreen: {
    width: PHONE_WIDTH,
    height: PHONE_HEIGHT,
    borderRadius: 20,
    overflow: "hidden",
    borderWidth: 3,
    borderColor: "rgba(255,255,255,0.2)",
  },
  mockScreen: {
    flex: 1,
  },

  // Slide 1: Camera
  cameraOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.3)",
    justifyContent: "space-between",
  },
  camHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingTop: 40,
    paddingHorizontal: 16,
  },
  camHeaderLeft: { width: 32 },
  camHeaderCenter: { flex: 1, alignItems: "center" },
  camHeaderRight: { width: 32, alignItems: "flex-end" },
  camTitle: {
    fontSize: 24,
    fontWeight: "800",
    color: "#FFFFFF",
  },
  camSubtitle: {
    fontSize: 13,
    color: "#FFFFFF",
    marginTop: 2,
  },
  camScanFrame: {
    marginHorizontal: 24,
    flex: 1,
    marginVertical: 50,
    borderWidth: 2,
    borderColor: "#FFFFFF",
    borderRadius: 16,
    borderStyle: "dashed",
  },
  camControls: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 32,
    paddingBottom: 40,
  },
  camSideBtn: {
    width: 44,
    height: 44,
    justifyContent: "center",
    alignItems: "center",
  },
  camCaptureBtn: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: "#FFFFFF",
    justifyContent: "center",
    alignItems: "center",
  },
  camCaptureBtnInner: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: "#F0F0F0",
    justifyContent: "center",
    alignItems: "center",
  },

  // Slide 2: Ingredients
  resultCardMock: {
    padding: 16,
    alignItems: "center",
  },
  scoreCircleMock: {
    width: 80,
    height: 80,
    borderRadius: 40,
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 8,
    marginTop: 16,
  },
  scoreNumMock: {
    fontSize: 32,
    fontWeight: "800",
    color: "#FFFFFF",
  },
  scoreOfMock: {
    fontSize: 11,
    fontWeight: "600",
    color: "rgba(255,255,255,0.8)",
    marginTop: -3,
  },
  gradeLabelMock: {
    fontSize: 18,
    fontWeight: "700",
    marginBottom: 4,
  },
  productNameMock: {
    fontSize: 15,
    fontWeight: "600",
    color: "#1A1A1A",
    marginBottom: 16,
  },
  sectionHeaderMock: {
    width: "100%",
    marginBottom: 8,
  },
  sectionTitleMock: {
    fontSize: 15,
    fontWeight: "700",
    color: "#1A1A1A",
  },
  ingredientCardMock: {
    width: "100%",
    backgroundColor: "#F8F9FA",
    borderRadius: 10,
    padding: 12,
    marginBottom: 8,
    gap: 4,
  },
  ingHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  ingNameRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    flex: 1,
  },
  ingDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
  },
  ingName: {
    fontSize: 13,
    fontWeight: "600",
    color: "#1A1A1A",
    flex: 1,
  },
  ingBadge: {
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 6,
  },
  ingScore: {
    fontSize: 12,
    fontWeight: "700",
  },
  ingImpact: {
    fontSize: 11,
    color: "#666",
    marginTop: 2,
  },

  // Slide 3: Benefits
  benefitsLayout: {
    flex: 1,
    padding: 20,
    justifyContent: "center",
    gap: 16,
  },
  benefitsHeader: {
    alignItems: "center",
    gap: 8,
    marginBottom: 8,
  },
  benefitsTitle: {
    fontSize: 22,
    fontWeight: "800",
    color: "#FFFFFF",
  },
  benefitRowMock: {
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
    backgroundColor: "rgba(255,255,255,0.08)",
    borderRadius: 14,
    padding: 14,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
  },
  benefitIconBox: {
    width: 44,
    height: 44,
    borderRadius: 12,
    backgroundColor: "rgba(255,255,255,0.1)",
    justifyContent: "center",
    alignItems: "center",
  },
  benefitTextBox: {
    flex: 1,
    gap: 2,
  },
  benefitTitleMock: {
    fontSize: 15,
    fontWeight: "700",
    color: "#FFFFFF",
  },
  benefitDescMock: {
    fontSize: 12,
    color: "rgba(255,255,255,0.6)",
  },
  benefitsBadge: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    marginTop: 8,
    paddingVertical: 10,
    backgroundColor: "rgba(255,255,255,0.06)",
    borderRadius: 10,
  },
  benefitsBadgeText: {
    fontSize: 12,
    color: "rgba(255,255,255,0.65)",
    fontWeight: "500",
  },

  // Slide 4: Product Details
  productImageArea: {
    height: 140,
    backgroundColor: "#E8E8E8",
    justifyContent: "center",
    alignItems: "center",
  },
  productImagePlaceholder: {
    alignItems: "center",
    gap: 4,
  },
  productImageText: {
    fontSize: 12,
    color: "#AAAAAA",
  },
  floatingBack: {
    position: "absolute",
    top: 40,
    left: 12,
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: "rgba(0,0,0,0.5)",
    justifyContent: "center",
    alignItems: "center",
  },
  floatingShare: {
    position: "absolute",
    top: 40,
    right: 12,
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: "rgba(0,0,0,0.5)",
    justifyContent: "center",
    alignItems: "center",
  },
  detailResultCard: {
    marginTop: -20,
    marginHorizontal: 12,
    backgroundColor: "#FFFFFF",
    borderRadius: 18,
    padding: 16,
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 3,
  },
  detailIngredient: {
    width: "100%",
    backgroundColor: "#F8F9FA",
    borderRadius: 10,
    padding: 12,
    marginTop: 12,
    gap: 4,
  },
  ingImpactBold: {
    fontSize: 12,
    fontWeight: "600",
    color: "#1A1A1A",
    marginTop: 4,
  },
  ingExplanation: {
    fontSize: 11,
    color: "#666",
    lineHeight: 16,
  },
  citationBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    marginTop: 6,
    backgroundColor: "rgba(17,138,178,0.1)",
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
    alignSelf: "flex-start",
  },
  citationBtnText: {
    fontSize: 10,
    fontWeight: "600",
    color: "#118AB2",
  },
  disclaimerMock: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginTop: 12,
    backgroundColor: "rgba(255,165,0,0.08)",
    padding: 10,
    borderRadius: 8,
    width: "100%",
  },
  disclaimerText: {
    fontSize: 10,
    color: "#888",
    flex: 1,
  },

  // Slide 5: History
  historyHeader: {
    paddingTop: 40,
    paddingHorizontal: 12,
    paddingBottom: 8,
    gap: 8,
  },
  histSearchBar: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    backgroundColor: "#F8F9FA",
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  histSearchText: {
    fontSize: 13,
    color: "#999",
  },
  histFilterRow: {
    flexDirection: "row",
    gap: 8,
  },
  histFilterBtn: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 4,
    backgroundColor: "#F8F9FA",
    borderRadius: 8,
    paddingVertical: 8,
  },
  histFilterText: {
    fontSize: 12,
    fontWeight: "600",
    color: "#1A1A1A",
  },
  histCount: {
    fontSize: 11,
    color: "#999",
  },
  histList: {
    paddingHorizontal: 12,
    paddingTop: 4,
    gap: 8,
    paddingBottom: 20,
  },
  histCard: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#FFFFFF",
    borderRadius: 12,
    padding: 10,
    borderLeftWidth: 3,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.04,
    shadowRadius: 4,
    elevation: 1,
  },
  histThumb: {
    width: 48,
    height: 48,
    borderRadius: 10,
    backgroundColor: "#F5F5F5",
    justifyContent: "center",
    alignItems: "center",
  },
  histCardContent: {
    flex: 1,
    marginLeft: 10,
    gap: 2,
  },
  histProductName: {
    fontSize: 13,
    fontWeight: "600",
    color: "#1A1A1A",
  },
  histMeta: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  histTime: {
    fontSize: 10,
    color: "#999",
  },
  histIngCount: {
    fontSize: 10,
    color: "#999",
  },
  histScoreArea: {
    alignItems: "center",
    gap: 2,
  },
  histScoreBadge: {
    width: 36,
    height: 36,
    borderRadius: 18,
    justifyContent: "center",
    alignItems: "center",
  },
  histScoreText: {
    fontSize: 14,
    fontWeight: "700",
    color: "#FFFFFF",
  },
  histGrade: {
    fontSize: 9,
    fontWeight: "600",
  },

  // Slide 6: Trust
  trustLayout: {
    flex: 1,
    padding: 20,
    justifyContent: "center",
    gap: 14,
  },
  trustShieldWrap: {
    alignItems: "center",
    marginBottom: 4,
  },
  trustRowMock: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    backgroundColor: "#FFFFFF",
    borderRadius: 12,
    padding: 14,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.04,
    shadowRadius: 4,
    elevation: 1,
  },
  trustIconBox: {
    width: 40,
    height: 40,
    borderRadius: 10,
    backgroundColor: "#F0FDF4",
    justifyContent: "center",
    alignItems: "center",
  },
  trustTextBox: {
    flex: 1,
    gap: 1,
  },
  trustTitleMock: {
    fontSize: 14,
    fontWeight: "700",
    color: "#1A1A1A",
  },
  trustDescMock: {
    fontSize: 11,
    color: "#666",
  },
  trustRatingRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 3,
    marginTop: 4,
  },
  trustRatingText: {
    fontSize: 12,
    fontWeight: "600",
    color: "#1A1A1A",
    marginLeft: 6,
  },
  trustQuote: {
    backgroundColor: "#FFFFFF",
    borderRadius: 12,
    padding: 14,
    borderLeftWidth: 3,
    borderLeftColor: "#06D6A0",
  },
  trustQuoteText: {
    fontSize: 12,
    fontStyle: "italic",
    color: "#444",
    lineHeight: 18,
  },

  // Slide 7: Brand
  brandLayout: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    padding: 24,
    gap: 16,
  },
  brandLogoMock: {
    width: 64,
    height: 64,
    borderRadius: 16,
  },
  brandNameMock: {
    fontSize: 28,
    fontWeight: "800",
    color: "#FFFFFF",
  },
  brandTaglineMock: {
    fontSize: 14,
    color: "rgba(255,255,255,0.7)",
    marginTop: -8,
  },
  brandMissionBox: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 10,
    backgroundColor: "rgba(255,255,255,0.1)",
    borderRadius: 14,
    padding: 16,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.1)",
  },
  brandMissionMock: {
    flex: 1,
    fontSize: 13,
    color: "rgba(255,255,255,0.85)",
    lineHeight: 19,
  },
  brandValuesList: {
    gap: 10,
    width: "100%",
  },
  brandValueRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  brandDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
  },
  brandValueText: {
    fontSize: 14,
    fontWeight: "600",
    color: "#FFFFFF",
  },
  brandCtaMock: {
    backgroundColor: "#FFFFFF",
    paddingHorizontal: 32,
    paddingVertical: 14,
    borderRadius: 12,
    marginTop: 4,
  },
  brandCtaText: {
    fontSize: 16,
    fontWeight: "700",
    color: "#118AB2",
  },
  brandPriceLine: {
    fontSize: 12,
    color: "rgba(255,255,255,0.55)",
  },
});
